# Generated by Django 4.2.13 on 2024-09-04 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stage_moov', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidats',
            name='Id_utilisateur',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='stage_moov.utilisateur'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('RH', 'RH'), ('Encadreur', 'Encadreur')], max_length=50),
        ),
    ]
