# Generated by Django 4.2.13 on 2024-08-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage_moov', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandes',
            name='Id_sujet',
        ),
        migrations.AddField(
            model_name='candidats',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('RH', 'RH'), ('Encadreur', 'Encadreur'), ('User_simple', 'User_simple')], max_length=50),
        ),
    ]
