# Generated by Django 5.0.7 on 2024-09-02 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage_moov', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidats',
            name='Id_utilisateur',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='stage_moov.utilisateur'),
        ),
    ]
