# Generated by Django 4.2.13 on 2024-08-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage_moov', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='utilisateur',
            name='stage_moov__Email_d4251a_idx',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='Nom_complet',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('rh', 'RH'), ('encadeur', 'Encadeur'), ('user_simple', 'User_simple')], max_length=100),
        ),
    ]