# Generated by Django 5.0.7 on 2024-08-21 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stage_moov', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sujet_stage',
            old_name='Description',
            new_name='description',
        ),
    ]
