# Generated by Django 4.2.13 on 2024-08-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage_moov', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sujet_stage',
            old_name='Description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='candidats',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='files',
            field=models.FileField(default='', upload_to='Evaluation/'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='content',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('RH', 'RH'), ('Encadreur', 'Encadreur'), ('User_simple', 'User_simple')], max_length=50),
        ),
    ]
