# Generated by Django 4.2.13 on 2024-08-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage_moov', '0002_remove_demandes_id_sujet_candidats_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidats',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
