# Generated by Django 4.2.13 on 2024-08-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage_moov', '0002_remove_utilisateur_stage_moov__email_d4251a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='Email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='Nom_complet',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('rh', 'RH'), ('encadeur', 'Encadeur'), ('user_simple', 'User_simple')], max_length=50),
        ),
    ]
