# Generated by Django 4.2.13 on 2024-08-31 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stage_moov', '0003_alter_candidats_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandes',
            old_name='Id_candidat',
            new_name='Nom_candidat',
        ),
    ]
