# Generated by Django 5.0.7 on 2024-08-26 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage_moov', '0003_choixsujet'),
    ]

    operations = [
        migrations.AddField(
            model_name='choixsujet',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stage_moov.utilisateur'),
        ),
        migrations.AlterField(
            model_name='choixsujet',
            name='stagiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage_moov.candidats'),
        ),
    ]
