# Generated by Django 4.2.13 on 2024-08-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage_moov', '0007_alter_evaluation_content_alter_evaluation_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(max_length=70),
        ),
    ]
