# Generated by Django 4.2.13 on 2024-08-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage_moov', '0009_alter_utilisateur_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('RH', 'RH'), ('Encadeur', 'Encadeur'), ('User_simple', 'User_simple')], max_length=50),
        ),
    ]
