# Generated by Django 5.0.7 on 2024-08-21 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stage_moov', '0010_alter_utilisateur_role'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='utilisateur',
            name='stage_moov__Email_d4251a_idx',
        ),
    ]
